package com.checkpoint.api.seed;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;

/**
 * Deterministic random helper for the seeder. Wraps {@link java.util.Random}
 * with a fixed seed so reruns on a fresh database produce the same data layout
 * (modulo entity UUIDs, which are generated by the database).
 */
final class SeedRandom {

    private final Random random;

    SeedRandom(long seed) {
        this.random = new Random(seed);
    }

    /**
     * Returns a uniformly random integer in {@code [minInclusive, maxInclusive]}.
     */
    int intBetween(int minInclusive, int maxInclusive) {
        if (maxInclusive < minInclusive) {
            return minInclusive;
        }
        return random.nextInt(maxInclusive - minInclusive + 1) + minInclusive;
    }

    /**
     * Returns true with the given probability ({@code 0.0 = never}, {@code 1.0 = always}).
     */
    boolean chance(double probability) {
        return random.nextDouble() < probability;
    }

    /**
     * Picks one element uniformly at random from the source list.
     */
    <T> T pick(List<T> source) {
        return source.get(random.nextInt(source.size()));
    }

    /**
     * Picks {@code count} distinct elements at random from {@code source}.
     * Caps at {@code source.size()} when {@code count} exceeds it.
     */
    <T> List<T> pickN(List<T> source, int count) {
        int safeCount = Math.min(count, source.size());
        if (safeCount <= 0) {
            return new ArrayList<>();
        }
        Set<Integer> indices = new HashSet<>(safeCount * 2);
        List<T> result = new ArrayList<>(safeCount);
        while (result.size() < safeCount) {
            int index = random.nextInt(source.size());
            if (indices.add(index)) {
                result.add(source.get(index));
            }
        }
        return result;
    }

    /**
     * Picks one element with probability proportional to {@code weights}.
     * The {@code weights} array must have the same length as {@code values}.
     */
    <T> T weightedPick(List<T> values, double[] weights) {
        double total = 0.0;
        for (double weight : weights) {
            total += weight;
        }
        double draw = random.nextDouble() * total;
        double cumulative = 0.0;
        for (int i = 0; i < values.size(); i++) {
            cumulative += weights[i];
            if (draw < cumulative) {
                return values.get(i);
            }
        }
        return values.get(values.size() - 1);
    }
}
