/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppProtectedRouteImport } from './routes/_app/_protected'
import { Route as AppGamesIndexRouteImport } from './routes/_app/games/index'
import { Route as AppGamesGameIdRouteImport } from './routes/_app/games/$gameId'
import { Route as AppProtectedProfileRouteImport } from './routes/_app/_protected/profile'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppProtectedRoute = AppProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIndexRoute = AppGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesGameIdRoute = AppGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectedProfileRoute = AppProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/profile': typeof AppProtectedProfileRoute
  '/games/$gameId': typeof AppGamesGameIdRoute
  '/games': typeof AppGamesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/': typeof AppIndexRoute
  '/profile': typeof AppProtectedProfileRoute
  '/games/$gameId': typeof AppGamesGameIdRoute
  '/games': typeof AppGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/_protected': typeof AppProtectedRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_protected/profile': typeof AppProtectedProfileRoute
  '/_app/games/$gameId': typeof AppGamesGameIdRoute
  '/_app/games/': typeof AppGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/' | '/profile' | '/games/$gameId' | '/games'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/profile' | '/games/$gameId' | '/games'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/_protected'
    | '/_auth/login'
    | '/_app/'
    | '/_app/_protected/profile'
    | '/_app/games/$gameId'
    | '/_app/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/_protected': {
      id: '/_app/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppProtectedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/': {
      id: '/_app/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof AppGamesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/$gameId': {
      id: '/_app/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AppGamesGameIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_protected/profile': {
      id: '/_app/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProtectedProfileRouteImport
      parentRoute: typeof AppProtectedRoute
    }
  }
}

interface AppProtectedRouteChildren {
  AppProtectedProfileRoute: typeof AppProtectedProfileRoute
}

const AppProtectedRouteChildren: AppProtectedRouteChildren = {
  AppProtectedProfileRoute: AppProtectedProfileRoute,
}

const AppProtectedRouteWithChildren = AppProtectedRoute._addFileChildren(
  AppProtectedRouteChildren,
)

interface AppRouteChildren {
  AppProtectedRoute: typeof AppProtectedRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppGamesGameIdRoute: typeof AppGamesGameIdRoute
  AppGamesIndexRoute: typeof AppGamesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProtectedRoute: AppProtectedRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppGamesGameIdRoute: AppGamesGameIdRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
