/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppRoadmapRouteImport } from './routes/_app/roadmap'
import { Route as AppLegalRouteImport } from './routes/_app/legal'
import { Route as AppLeaderboardRouteImport } from './routes/_app/leaderboard'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppProtectedRouteImport } from './routes/_app/_protected'
import { Route as AppNewsIndexRouteImport } from './routes/_app/news/index'
import { Route as AppMembersIndexRouteImport } from './routes/_app/members/index'
import { Route as AppListsIndexRouteImport } from './routes/_app/lists/index'
import { Route as AppGamesIndexRouteImport } from './routes/_app/games/index'
import { Route as AppProfileUsernameRouteImport } from './routes/_app/profile/$username'
import { Route as AppPlaysIdRouteImport } from './routes/_app/plays.$id'
import { Route as AppNewsNewsIdRouteImport } from './routes/_app/news/$newsId'
import { Route as AppMembersAllRouteImport } from './routes/_app/members/all'
import { Route as AppListsBrowseRouteImport } from './routes/_app/lists/browse'
import { Route as AppListsListIdRouteImport } from './routes/_app/lists/$listId'
import { Route as AppGamesFilteredRouteImport } from './routes/_app/games/filtered'
import { Route as AppGamesGameIdRouteImport } from './routes/_app/games/$gameId'
import { Route as AppProtectedProfileRouteImport } from './routes/_app/_protected/profile'
import { Route as AppProtectedNotificationsRouteImport } from './routes/_app/_protected/notifications'
import { Route as AppProtectedSettingsRouteRouteImport } from './routes/_app/_protected/settings/route'
import { Route as AppProtectedSettingsIndexRouteImport } from './routes/_app/_protected/settings/index'
import { Route as AppProtectedFeedIndexRouteImport } from './routes/_app/_protected/feed/index'
import { Route as AppProfileUsernameListsRouteImport } from './routes/_app/profile_.$username.lists'
import { Route as AppProfileUsernameGamesRouteImport } from './routes/_app/profile_.$username.games'
import { Route as AppProfileUsernameCompareRouteImport } from './routes/_app/profile_.$username.compare'
import { Route as AppProfileUsernameBadgesRouteImport } from './routes/_app/profile_.$username.badges'
import { Route as AppGamesGameIdListsRouteImport } from './routes/_app/games/$gameId_.lists'
import { Route as AppProtectedSettingsSecurityRouteImport } from './routes/_app/_protected/settings/security'
import { Route as AppProtectedSettingsProfileRouteImport } from './routes/_app/_protected/settings/profile'
import { Route as AppProtectedSettingsNotificationsRouteImport } from './routes/_app/_protected/settings/notifications'
import { Route as AppProtectedSettingsIntegrationsRouteImport } from './routes/_app/_protected/settings/integrations'
import { Route as AppProtectedSettingsAppearanceRouteImport } from './routes/_app/_protected/settings/appearance'
import { Route as AppProtectedListsNewRouteImport } from './routes/_app/_protected/lists/new'
import { Route as AppProtectedGamesPopularWithFriendsRouteImport } from './routes/_app/_protected/games/popular-with-friends'
import { Route as AppProtectedUsernameTagsIndexRouteImport } from './routes/_app/_protected/$username/tags/index'
import { Route as AppProtectedListsListIdEditRouteImport } from './routes/_app/_protected/lists/$listId/edit'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AppRoadmapRoute = AppRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AppRoute,
} as any)
const AppLegalRoute = AppLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectedRoute = AppProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsIndexRoute = AppNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersIndexRoute = AppMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => AppRoute,
} as any)
const AppListsIndexRoute = AppListsIndexRouteImport.update({
  id: '/lists/',
  path: '/lists/',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIndexRoute = AppGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUsernameRoute = AppProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaysIdRoute = AppPlaysIdRouteImport.update({
  id: '/plays/$id',
  path: '/plays/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsNewsIdRoute = AppNewsNewsIdRouteImport.update({
  id: '/news/$newsId',
  path: '/news/$newsId',
  getParentRoute: () => AppRoute,
} as any)
const AppMembersAllRoute = AppMembersAllRouteImport.update({
  id: '/members/all',
  path: '/members/all',
  getParentRoute: () => AppRoute,
} as any)
const AppListsBrowseRoute = AppListsBrowseRouteImport.update({
  id: '/lists/browse',
  path: '/lists/browse',
  getParentRoute: () => AppRoute,
} as any)
const AppListsListIdRoute = AppListsListIdRouteImport.update({
  id: '/lists/$listId',
  path: '/lists/$listId',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesFilteredRoute = AppGamesFilteredRouteImport.update({
  id: '/games/filtered',
  path: '/games/filtered',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesGameIdRoute = AppGamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectedProfileRoute = AppProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppProtectedRoute,
} as any)
const AppProtectedNotificationsRoute =
  AppProtectedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedSettingsRouteRoute =
  AppProtectedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedSettingsIndexRoute =
  AppProtectedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProtectedSettingsRouteRoute,
  } as any)
const AppProtectedFeedIndexRoute = AppProtectedFeedIndexRouteImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => AppProtectedRoute,
} as any)
const AppProfileUsernameListsRoute = AppProfileUsernameListsRouteImport.update({
  id: '/profile_/$username/lists',
  path: '/profile/$username/lists',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUsernameGamesRoute = AppProfileUsernameGamesRouteImport.update({
  id: '/profile_/$username/games',
  path: '/profile/$username/games',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileUsernameCompareRoute =
  AppProfileUsernameCompareRouteImport.update({
    id: '/profile_/$username/compare',
    path: '/profile/$username/compare',
    getParentRoute: () => AppRoute,
  } as any)
const AppProfileUsernameBadgesRoute =
  AppProfileUsernameBadgesRouteImport.update({
    id: '/profile_/$username/badges',
    path: '/profile/$username/badges',
    getParentRoute: () => AppRoute,
  } as any)
const AppGamesGameIdListsRoute = AppGamesGameIdListsRouteImport.update({
  id: '/games/$gameId_/lists',
  path: '/games/$gameId/lists',
  getParentRoute: () => AppRoute,
} as any)
const AppProtectedSettingsSecurityRoute =
  AppProtectedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AppProtectedSettingsRouteRoute,
  } as any)
const AppProtectedSettingsProfileRoute =
  AppProtectedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AppProtectedSettingsRouteRoute,
  } as any)
const AppProtectedSettingsNotificationsRoute =
  AppProtectedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppProtectedSettingsRouteRoute,
  } as any)
const AppProtectedSettingsIntegrationsRoute =
  AppProtectedSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AppProtectedSettingsRouteRoute,
  } as any)
const AppProtectedSettingsAppearanceRoute =
  AppProtectedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AppProtectedSettingsRouteRoute,
  } as any)
const AppProtectedListsNewRoute = AppProtectedListsNewRouteImport.update({
  id: '/lists/new',
  path: '/lists/new',
  getParentRoute: () => AppProtectedRoute,
} as any)
const AppProtectedGamesPopularWithFriendsRoute =
  AppProtectedGamesPopularWithFriendsRouteImport.update({
    id: '/games/popular-with-friends',
    path: '/games/popular-with-friends',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedUsernameTagsIndexRoute =
  AppProtectedUsernameTagsIndexRouteImport.update({
    id: '/$username/tags/',
    path: '/$username/tags/',
    getParentRoute: () => AppProtectedRoute,
  } as any)
const AppProtectedListsListIdEditRoute =
  AppProtectedListsListIdEditRouteImport.update({
    id: '/lists/$listId/edit',
    path: '/lists/$listId/edit',
    getParentRoute: () => AppProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/legal': typeof AppLegalRoute
  '/roadmap': typeof AppRoadmapRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/settings': typeof AppProtectedSettingsRouteRouteWithChildren
  '/notifications': typeof AppProtectedNotificationsRoute
  '/profile': typeof AppProtectedProfileRoute
  '/games/$gameId': typeof AppGamesGameIdRoute
  '/games/filtered': typeof AppGamesFilteredRoute
  '/lists/$listId': typeof AppListsListIdRoute
  '/lists/browse': typeof AppListsBrowseRoute
  '/members/all': typeof AppMembersAllRoute
  '/news/$newsId': typeof AppNewsNewsIdRoute
  '/plays/$id': typeof AppPlaysIdRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/games/': typeof AppGamesIndexRoute
  '/lists/': typeof AppListsIndexRoute
  '/members/': typeof AppMembersIndexRoute
  '/news/': typeof AppNewsIndexRoute
  '/games/popular-with-friends': typeof AppProtectedGamesPopularWithFriendsRoute
  '/lists/new': typeof AppProtectedListsNewRoute
  '/settings/appearance': typeof AppProtectedSettingsAppearanceRoute
  '/settings/integrations': typeof AppProtectedSettingsIntegrationsRoute
  '/settings/notifications': typeof AppProtectedSettingsNotificationsRoute
  '/settings/profile': typeof AppProtectedSettingsProfileRoute
  '/settings/security': typeof AppProtectedSettingsSecurityRoute
  '/games/$gameId/lists': typeof AppGamesGameIdListsRoute
  '/profile/$username/badges': typeof AppProfileUsernameBadgesRoute
  '/profile/$username/compare': typeof AppProfileUsernameCompareRoute
  '/profile/$username/games': typeof AppProfileUsernameGamesRoute
  '/profile/$username/lists': typeof AppProfileUsernameListsRoute
  '/feed/': typeof AppProtectedFeedIndexRoute
  '/settings/': typeof AppProtectedSettingsIndexRoute
  '/lists/$listId/edit': typeof AppProtectedListsListIdEditRoute
  '/$username/tags/': typeof AppProtectedUsernameTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/leaderboard': typeof AppLeaderboardRoute
  '/legal': typeof AppLegalRoute
  '/roadmap': typeof AppRoadmapRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/notifications': typeof AppProtectedNotificationsRoute
  '/profile': typeof AppProtectedProfileRoute
  '/games/$gameId': typeof AppGamesGameIdRoute
  '/games/filtered': typeof AppGamesFilteredRoute
  '/lists/$listId': typeof AppListsListIdRoute
  '/lists/browse': typeof AppListsBrowseRoute
  '/members/all': typeof AppMembersAllRoute
  '/news/$newsId': typeof AppNewsNewsIdRoute
  '/plays/$id': typeof AppPlaysIdRoute
  '/profile/$username': typeof AppProfileUsernameRoute
  '/games': typeof AppGamesIndexRoute
  '/lists': typeof AppListsIndexRoute
  '/members': typeof AppMembersIndexRoute
  '/news': typeof AppNewsIndexRoute
  '/games/popular-with-friends': typeof AppProtectedGamesPopularWithFriendsRoute
  '/lists/new': typeof AppProtectedListsNewRoute
  '/settings/appearance': typeof AppProtectedSettingsAppearanceRoute
  '/settings/integrations': typeof AppProtectedSettingsIntegrationsRoute
  '/settings/notifications': typeof AppProtectedSettingsNotificationsRoute
  '/settings/profile': typeof AppProtectedSettingsProfileRoute
  '/settings/security': typeof AppProtectedSettingsSecurityRoute
  '/games/$gameId/lists': typeof AppGamesGameIdListsRoute
  '/profile/$username/badges': typeof AppProfileUsernameBadgesRoute
  '/profile/$username/compare': typeof AppProfileUsernameCompareRoute
  '/profile/$username/games': typeof AppProfileUsernameGamesRoute
  '/profile/$username/lists': typeof AppProfileUsernameListsRoute
  '/feed': typeof AppProtectedFeedIndexRoute
  '/settings': typeof AppProtectedSettingsIndexRoute
  '/lists/$listId/edit': typeof AppProtectedListsListIdEditRoute
  '/$username/tags': typeof AppProtectedUsernameTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/_protected': typeof AppProtectedRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/leaderboard': typeof AppLeaderboardRoute
  '/_app/legal': typeof AppLegalRoute
  '/_app/roadmap': typeof AppRoadmapRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_protected/settings': typeof AppProtectedSettingsRouteRouteWithChildren
  '/_app/_protected/notifications': typeof AppProtectedNotificationsRoute
  '/_app/_protected/profile': typeof AppProtectedProfileRoute
  '/_app/games/$gameId': typeof AppGamesGameIdRoute
  '/_app/games/filtered': typeof AppGamesFilteredRoute
  '/_app/lists/$listId': typeof AppListsListIdRoute
  '/_app/lists/browse': typeof AppListsBrowseRoute
  '/_app/members/all': typeof AppMembersAllRoute
  '/_app/news/$newsId': typeof AppNewsNewsIdRoute
  '/_app/plays/$id': typeof AppPlaysIdRoute
  '/_app/profile/$username': typeof AppProfileUsernameRoute
  '/_app/games/': typeof AppGamesIndexRoute
  '/_app/lists/': typeof AppListsIndexRoute
  '/_app/members/': typeof AppMembersIndexRoute
  '/_app/news/': typeof AppNewsIndexRoute
  '/_app/_protected/games/popular-with-friends': typeof AppProtectedGamesPopularWithFriendsRoute
  '/_app/_protected/lists/new': typeof AppProtectedListsNewRoute
  '/_app/_protected/settings/appearance': typeof AppProtectedSettingsAppearanceRoute
  '/_app/_protected/settings/integrations': typeof AppProtectedSettingsIntegrationsRoute
  '/_app/_protected/settings/notifications': typeof AppProtectedSettingsNotificationsRoute
  '/_app/_protected/settings/profile': typeof AppProtectedSettingsProfileRoute
  '/_app/_protected/settings/security': typeof AppProtectedSettingsSecurityRoute
  '/_app/games/$gameId_/lists': typeof AppGamesGameIdListsRoute
  '/_app/profile_/$username/badges': typeof AppProfileUsernameBadgesRoute
  '/_app/profile_/$username/compare': typeof AppProfileUsernameCompareRoute
  '/_app/profile_/$username/games': typeof AppProfileUsernameGamesRoute
  '/_app/profile_/$username/lists': typeof AppProfileUsernameListsRoute
  '/_app/_protected/feed/': typeof AppProtectedFeedIndexRoute
  '/_app/_protected/settings/': typeof AppProtectedSettingsIndexRoute
  '/_app/_protected/lists/$listId/edit': typeof AppProtectedListsListIdEditRoute
  '/_app/_protected/$username/tags/': typeof AppProtectedUsernameTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/legal'
    | '/roadmap'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/notifications'
    | '/profile'
    | '/games/$gameId'
    | '/games/filtered'
    | '/lists/$listId'
    | '/lists/browse'
    | '/members/all'
    | '/news/$newsId'
    | '/plays/$id'
    | '/profile/$username'
    | '/games/'
    | '/lists/'
    | '/members/'
    | '/news/'
    | '/games/popular-with-friends'
    | '/lists/new'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/games/$gameId/lists'
    | '/profile/$username/badges'
    | '/profile/$username/compare'
    | '/profile/$username/games'
    | '/profile/$username/lists'
    | '/feed/'
    | '/settings/'
    | '/lists/$listId/edit'
    | '/$username/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/leaderboard'
    | '/legal'
    | '/roadmap'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/notifications'
    | '/profile'
    | '/games/$gameId'
    | '/games/filtered'
    | '/lists/$listId'
    | '/lists/browse'
    | '/members/all'
    | '/news/$newsId'
    | '/plays/$id'
    | '/profile/$username'
    | '/games'
    | '/lists'
    | '/members'
    | '/news'
    | '/games/popular-with-friends'
    | '/lists/new'
    | '/settings/appearance'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/games/$gameId/lists'
    | '/profile/$username/badges'
    | '/profile/$username/compare'
    | '/profile/$username/games'
    | '/profile/$username/lists'
    | '/feed'
    | '/settings'
    | '/lists/$listId/edit'
    | '/$username/tags'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/_protected'
    | '/_app/about'
    | '/_app/leaderboard'
    | '/_app/legal'
    | '/_app/roadmap'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_app/'
    | '/_app/_protected/settings'
    | '/_app/_protected/notifications'
    | '/_app/_protected/profile'
    | '/_app/games/$gameId'
    | '/_app/games/filtered'
    | '/_app/lists/$listId'
    | '/_app/lists/browse'
    | '/_app/members/all'
    | '/_app/news/$newsId'
    | '/_app/plays/$id'
    | '/_app/profile/$username'
    | '/_app/games/'
    | '/_app/lists/'
    | '/_app/members/'
    | '/_app/news/'
    | '/_app/_protected/games/popular-with-friends'
    | '/_app/_protected/lists/new'
    | '/_app/_protected/settings/appearance'
    | '/_app/_protected/settings/integrations'
    | '/_app/_protected/settings/notifications'
    | '/_app/_protected/settings/profile'
    | '/_app/_protected/settings/security'
    | '/_app/games/$gameId_/lists'
    | '/_app/profile_/$username/badges'
    | '/_app/profile_/$username/compare'
    | '/_app/profile_/$username/games'
    | '/_app/profile_/$username/lists'
    | '/_app/_protected/feed/'
    | '/_app/_protected/settings/'
    | '/_app/_protected/lists/$listId/edit'
    | '/_app/_protected/$username/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/roadmap': {
      id: '/_app/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AppRoadmapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/legal': {
      id: '/_app/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof AppLegalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboard': {
      id: '/_app/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_protected': {
      id: '/_app/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppProtectedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/': {
      id: '/_app/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof AppNewsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/': {
      id: '/_app/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof AppMembersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/': {
      id: '/_app/lists/'
      path: '/lists'
      fullPath: '/lists/'
      preLoaderRoute: typeof AppListsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/': {
      id: '/_app/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof AppGamesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/$username': {
      id: '/_app/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plays/$id': {
      id: '/_app/plays/$id'
      path: '/plays/$id'
      fullPath: '/plays/$id'
      preLoaderRoute: typeof AppPlaysIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/news/$newsId': {
      id: '/_app/news/$newsId'
      path: '/news/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof AppNewsNewsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/members/all': {
      id: '/_app/members/all'
      path: '/members/all'
      fullPath: '/members/all'
      preLoaderRoute: typeof AppMembersAllRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/browse': {
      id: '/_app/lists/browse'
      path: '/lists/browse'
      fullPath: '/lists/browse'
      preLoaderRoute: typeof AppListsBrowseRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lists/$listId': {
      id: '/_app/lists/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof AppListsListIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/filtered': {
      id: '/_app/games/filtered'
      path: '/games/filtered'
      fullPath: '/games/filtered'
      preLoaderRoute: typeof AppGamesFilteredRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/$gameId': {
      id: '/_app/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof AppGamesGameIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_protected/profile': {
      id: '/_app/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProtectedProfileRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/_protected/notifications': {
      id: '/_app/_protected/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppProtectedNotificationsRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/_protected/settings': {
      id: '/_app/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppProtectedSettingsRouteRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/_protected/settings/': {
      id: '/_app/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppProtectedSettingsIndexRouteImport
      parentRoute: typeof AppProtectedSettingsRouteRoute
    }
    '/_app/_protected/feed/': {
      id: '/_app/_protected/feed/'
      path: '/feed'
      fullPath: '/feed/'
      preLoaderRoute: typeof AppProtectedFeedIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/profile_/$username/lists': {
      id: '/_app/profile_/$username/lists'
      path: '/profile/$username/lists'
      fullPath: '/profile/$username/lists'
      preLoaderRoute: typeof AppProfileUsernameListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile_/$username/games': {
      id: '/_app/profile_/$username/games'
      path: '/profile/$username/games'
      fullPath: '/profile/$username/games'
      preLoaderRoute: typeof AppProfileUsernameGamesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile_/$username/compare': {
      id: '/_app/profile_/$username/compare'
      path: '/profile/$username/compare'
      fullPath: '/profile/$username/compare'
      preLoaderRoute: typeof AppProfileUsernameCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile_/$username/badges': {
      id: '/_app/profile_/$username/badges'
      path: '/profile/$username/badges'
      fullPath: '/profile/$username/badges'
      preLoaderRoute: typeof AppProfileUsernameBadgesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/$gameId_/lists': {
      id: '/_app/games/$gameId_/lists'
      path: '/games/$gameId/lists'
      fullPath: '/games/$gameId/lists'
      preLoaderRoute: typeof AppGamesGameIdListsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/_protected/settings/security': {
      id: '/_app/_protected/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppProtectedSettingsSecurityRouteImport
      parentRoute: typeof AppProtectedSettingsRouteRoute
    }
    '/_app/_protected/settings/profile': {
      id: '/_app/_protected/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AppProtectedSettingsProfileRouteImport
      parentRoute: typeof AppProtectedSettingsRouteRoute
    }
    '/_app/_protected/settings/notifications': {
      id: '/_app/_protected/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppProtectedSettingsNotificationsRouteImport
      parentRoute: typeof AppProtectedSettingsRouteRoute
    }
    '/_app/_protected/settings/integrations': {
      id: '/_app/_protected/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppProtectedSettingsIntegrationsRouteImport
      parentRoute: typeof AppProtectedSettingsRouteRoute
    }
    '/_app/_protected/settings/appearance': {
      id: '/_app/_protected/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppProtectedSettingsAppearanceRouteImport
      parentRoute: typeof AppProtectedSettingsRouteRoute
    }
    '/_app/_protected/lists/new': {
      id: '/_app/_protected/lists/new'
      path: '/lists/new'
      fullPath: '/lists/new'
      preLoaderRoute: typeof AppProtectedListsNewRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/_protected/games/popular-with-friends': {
      id: '/_app/_protected/games/popular-with-friends'
      path: '/games/popular-with-friends'
      fullPath: '/games/popular-with-friends'
      preLoaderRoute: typeof AppProtectedGamesPopularWithFriendsRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/_protected/$username/tags/': {
      id: '/_app/_protected/$username/tags/'
      path: '/$username/tags'
      fullPath: '/$username/tags/'
      preLoaderRoute: typeof AppProtectedUsernameTagsIndexRouteImport
      parentRoute: typeof AppProtectedRoute
    }
    '/_app/_protected/lists/$listId/edit': {
      id: '/_app/_protected/lists/$listId/edit'
      path: '/lists/$listId/edit'
      fullPath: '/lists/$listId/edit'
      preLoaderRoute: typeof AppProtectedListsListIdEditRouteImport
      parentRoute: typeof AppProtectedRoute
    }
  }
}

interface AppProtectedSettingsRouteRouteChildren {
  AppProtectedSettingsAppearanceRoute: typeof AppProtectedSettingsAppearanceRoute
  AppProtectedSettingsIntegrationsRoute: typeof AppProtectedSettingsIntegrationsRoute
  AppProtectedSettingsNotificationsRoute: typeof AppProtectedSettingsNotificationsRoute
  AppProtectedSettingsProfileRoute: typeof AppProtectedSettingsProfileRoute
  AppProtectedSettingsSecurityRoute: typeof AppProtectedSettingsSecurityRoute
  AppProtectedSettingsIndexRoute: typeof AppProtectedSettingsIndexRoute
}

const AppProtectedSettingsRouteRouteChildren: AppProtectedSettingsRouteRouteChildren =
  {
    AppProtectedSettingsAppearanceRoute: AppProtectedSettingsAppearanceRoute,
    AppProtectedSettingsIntegrationsRoute:
      AppProtectedSettingsIntegrationsRoute,
    AppProtectedSettingsNotificationsRoute:
      AppProtectedSettingsNotificationsRoute,
    AppProtectedSettingsProfileRoute: AppProtectedSettingsProfileRoute,
    AppProtectedSettingsSecurityRoute: AppProtectedSettingsSecurityRoute,
    AppProtectedSettingsIndexRoute: AppProtectedSettingsIndexRoute,
  }

const AppProtectedSettingsRouteRouteWithChildren =
  AppProtectedSettingsRouteRoute._addFileChildren(
    AppProtectedSettingsRouteRouteChildren,
  )

interface AppProtectedRouteChildren {
  AppProtectedSettingsRouteRoute: typeof AppProtectedSettingsRouteRouteWithChildren
  AppProtectedNotificationsRoute: typeof AppProtectedNotificationsRoute
  AppProtectedProfileRoute: typeof AppProtectedProfileRoute
  AppProtectedGamesPopularWithFriendsRoute: typeof AppProtectedGamesPopularWithFriendsRoute
  AppProtectedListsNewRoute: typeof AppProtectedListsNewRoute
  AppProtectedFeedIndexRoute: typeof AppProtectedFeedIndexRoute
  AppProtectedListsListIdEditRoute: typeof AppProtectedListsListIdEditRoute
  AppProtectedUsernameTagsIndexRoute: typeof AppProtectedUsernameTagsIndexRoute
}

const AppProtectedRouteChildren: AppProtectedRouteChildren = {
  AppProtectedSettingsRouteRoute: AppProtectedSettingsRouteRouteWithChildren,
  AppProtectedNotificationsRoute: AppProtectedNotificationsRoute,
  AppProtectedProfileRoute: AppProtectedProfileRoute,
  AppProtectedGamesPopularWithFriendsRoute:
    AppProtectedGamesPopularWithFriendsRoute,
  AppProtectedListsNewRoute: AppProtectedListsNewRoute,
  AppProtectedFeedIndexRoute: AppProtectedFeedIndexRoute,
  AppProtectedListsListIdEditRoute: AppProtectedListsListIdEditRoute,
  AppProtectedUsernameTagsIndexRoute: AppProtectedUsernameTagsIndexRoute,
}

const AppProtectedRouteWithChildren = AppProtectedRoute._addFileChildren(
  AppProtectedRouteChildren,
)

interface AppRouteChildren {
  AppProtectedRoute: typeof AppProtectedRouteWithChildren
  AppAboutRoute: typeof AppAboutRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppLegalRoute: typeof AppLegalRoute
  AppRoadmapRoute: typeof AppRoadmapRoute
  AppIndexRoute: typeof AppIndexRoute
  AppGamesGameIdRoute: typeof AppGamesGameIdRoute
  AppGamesFilteredRoute: typeof AppGamesFilteredRoute
  AppListsListIdRoute: typeof AppListsListIdRoute
  AppListsBrowseRoute: typeof AppListsBrowseRoute
  AppMembersAllRoute: typeof AppMembersAllRoute
  AppNewsNewsIdRoute: typeof AppNewsNewsIdRoute
  AppPlaysIdRoute: typeof AppPlaysIdRoute
  AppProfileUsernameRoute: typeof AppProfileUsernameRoute
  AppGamesIndexRoute: typeof AppGamesIndexRoute
  AppListsIndexRoute: typeof AppListsIndexRoute
  AppMembersIndexRoute: typeof AppMembersIndexRoute
  AppNewsIndexRoute: typeof AppNewsIndexRoute
  AppGamesGameIdListsRoute: typeof AppGamesGameIdListsRoute
  AppProfileUsernameBadgesRoute: typeof AppProfileUsernameBadgesRoute
  AppProfileUsernameCompareRoute: typeof AppProfileUsernameCompareRoute
  AppProfileUsernameGamesRoute: typeof AppProfileUsernameGamesRoute
  AppProfileUsernameListsRoute: typeof AppProfileUsernameListsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProtectedRoute: AppProtectedRouteWithChildren,
  AppAboutRoute: AppAboutRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppLegalRoute: AppLegalRoute,
  AppRoadmapRoute: AppRoadmapRoute,
  AppIndexRoute: AppIndexRoute,
  AppGamesGameIdRoute: AppGamesGameIdRoute,
  AppGamesFilteredRoute: AppGamesFilteredRoute,
  AppListsListIdRoute: AppListsListIdRoute,
  AppListsBrowseRoute: AppListsBrowseRoute,
  AppMembersAllRoute: AppMembersAllRoute,
  AppNewsNewsIdRoute: AppNewsNewsIdRoute,
  AppPlaysIdRoute: AppPlaysIdRoute,
  AppProfileUsernameRoute: AppProfileUsernameRoute,
  AppGamesIndexRoute: AppGamesIndexRoute,
  AppListsIndexRoute: AppListsIndexRoute,
  AppMembersIndexRoute: AppMembersIndexRoute,
  AppNewsIndexRoute: AppNewsIndexRoute,
  AppGamesGameIdListsRoute: AppGamesGameIdListsRoute,
  AppProfileUsernameBadgesRoute: AppProfileUsernameBadgesRoute,
  AppProfileUsernameCompareRoute: AppProfileUsernameCompareRoute,
  AppProfileUsernameGamesRoute: AppProfileUsernameGamesRoute,
  AppProfileUsernameListsRoute: AppProfileUsernameListsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
